import React, { useContext } from 'react';
import { SettingsContext } from '../../context/SettingsContext.jsx';

export const NotificationSettings = () => {
  const { settings, updateSetting } = useContext(SettingsContext);

  const handleNotifToggle = (key, val) => {
    updateSetting('notifications', key, val);
  };

  const handleParkingPrefToggle = (key, val) => {
    updateSetting('parkingPreferences', key, val);
  };

  return (
    <div className="settings-card">
      <h3><i className="fa-solid fa-bell"></i> Notifications & Alerts</h3>
      
      <div className="settings-group">
        <h4 style={{ color: 'var(--primary)', fontFamily: 'Rajdhani', fontSize: '1.2rem', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '0.25rem', marginTop: '0.5rem' }}>
          Alert Broadcast Channels
        </h4>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Match Event Alerts</span>
            <p>Get notified about goals, VIP arrivals, and schedules.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.notifications?.matchAlerts} 
              onChange={(e) => handleNotifToggle('matchAlerts', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Parking Space Alerts</span>
            <p>Get notifications when parking zones reach capacity.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.notifications?.parkingAlerts} 
              onChange={(e) => handleNotifToggle('parkingAlerts', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Weather Severity Alerts</span>
            <p>Get notified of heavy rain, high winds, or storm events.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.notifications?.weatherAlerts} 
              onChange={(e) => handleNotifToggle('weatherAlerts', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>AI Predictive Insight Alerts</span>
            <p>Get recommendations generated by the AI copilot.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.notifications?.aiAlerts} 
              onChange={(e) => handleNotifToggle('aiAlerts', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Security Incident Alerts</span>
            <p>Direct notification of threat alerts and incident events.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.notifications?.securityAlerts} 
              onChange={(e) => handleNotifToggle('securityAlerts', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Emergency Evacuation Broadcasts</span>
            <p>Loud sound and overlay alarms on the dashboard panel.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.notifications?.emergencyAlerts} 
              onChange={(e) => handleNotifToggle('emergencyAlerts', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        {/* Weather Preferences */}
        <h4 style={{ color: 'var(--primary)', fontFamily: 'Rajdhani', fontSize: '1.2rem', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '0.25rem', marginTop: '1.5rem' }}>
          Weather Preferences
        </h4>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Temperature Unit</span>
            <p>Choose Celsius or Fahrenheit representation.</p>
          </div>
          <div className="size-picker" style={{ width: '120px', marginTop: 0 }}>
            <div 
              className={`size-chip ${settings.weatherUnit === 'C' ? 'active' : ''}`}
              onClick={() => updateSetting(null, 'weatherUnit', 'C')}
              style={{ padding: '0.4rem 0.6rem' }}
            >
              °C
            </div>
            <div 
              className={`size-chip ${settings.weatherUnit === 'F' ? 'active' : ''}`}
              onClick={() => updateSetting(null, 'weatherUnit', 'F')}
              style={{ padding: '0.4rem 0.6rem' }}
            >
              °F
            </div>
          </div>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Wind Speed Unit</span>
            <p>Choose metric or imperial velocity calculation.</p>
          </div>
          <div className="size-picker" style={{ width: '150px', marginTop: 0 }}>
            <div 
              className={`size-chip ${settings.windSpeedUnit === 'km/h' ? 'active' : ''}`}
              onClick={() => updateSetting(null, 'windSpeedUnit', 'km/h')}
              style={{ padding: '0.4rem 0.6rem' }}
            >
              km/h
            </div>
            <div 
              className={`size-chip ${settings.windSpeedUnit === 'mph' ? 'active' : ''}`}
              onClick={() => updateSetting(null, 'windSpeedUnit', 'mph')}
              style={{ padding: '0.4rem 0.6rem' }}
            >
              mph
            </div>
          </div>
        </div>

        {/* Parking Preferences */}
        <h4 style={{ color: 'var(--primary)', fontFamily: 'Rajdhani', fontSize: '1.2rem', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '0.25rem', marginTop: '1.5rem' }}>
          Parking Preferences
        </h4>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Smart Parking Suggestions</span>
            <p>Allow AI to offer dynamic suggestions for visitors.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.parkingPreferences?.suggestions} 
              onChange={(e) => handleParkingPrefToggle('suggestions', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Show Available Slots Indicator</span>
            <p>Render exact live number of unoccupied VIP/EV bays.</p>
          </div>
          <label className="cyber-switch">
            <input 
              type="checkbox" 
              checked={settings.parkingPreferences?.availableSlots} 
              onChange={(e) => handleParkingPrefToggle('availableSlots', e.target.checked)} 
            />
            <span className="cyber-slider"></span>
          </label>
        </div>

        <div className="settings-row">
          <div className="settings-label-block">
            <span>Preferred Parking Zone</span>
            <p>Set the default priority zone for reservation logs.</p>
          </div>
          <div style={{ width: '150px' }}>
            <select 
              value={settings.parkingPreferences?.preferredZone || 'Zone A'} 
              onChange={(e) => handleParkingPrefToggle('preferredZone', e.target.value)} 
              className="cyber-field cyber-select-box"
              style={{ padding: '0.4rem 0.8rem' }}
            >
              <option value="Zone A">Zone A</option>
              <option value="Zone B">Zone B</option>
              <option value="VIP Area">VIP Zone</option>
              <option value="EV Port">EV Port</option>
            </select>
          </div>
        </div>
      </div>
    </div>
  );
};
export default NotificationSettings;
